// Generate the index.html that lists all archived reports

import Handlebars from "handlebars";
import type { Theme } from "../types.js";
import { buildCSS } from "../renderer/themes.js";

type ReportEntry = {
  path: string;
  label: string;
};

const TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <title>Weekly Reports</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Archive of weekly GitHub activity reports" />
  <style>{{{css}}}</style>
</head>
<body>
<div class="container">
  <header class="header">
    <div class="header-text">
      <h1>Weekly Reports</h1>
      <p class="date-range">All generated reports</p>
    </div>
  </header>

  <div class="section">
    <h2>Reports</h2>
    <table class="repo-table">
      <thead><tr><th>Week</th><th>Link</th></tr></thead>
      <tbody>
        {{#each reports}}
        <tr>
          <td>{{this.label}}</td>
          <td><a href="{{this.path}}/">View Report</a></td>
        </tr>
        {{/each}}
      </tbody>
    </table>
  </div>

  <footer class="footer">
    <p>Generated by <a href="https://deariary.com?utm_source=github-weekly-reporter&utm_medium=footer">deariary</a></p>
  </footer>
</div>
</body>
</html>`;

export const renderIndexPage = (reportPaths: string[], theme: Theme = "default"): string => {
  const reports: ReportEntry[] = reportPaths
    .sort()
    .reverse()
    .map((p) => ({ path: p, label: p.replace("/", " ") }));

  const template = Handlebars.compile(TEMPLATE);
  return template({ reports, css: buildCSS(theme) });
};
