// HTML fragment builders for each report section

import type {
  WeeklyReportData,
  DailyCommitCount,
  LanguageBreakdown,
  RepositoryActivity,
} from "../types.js";

const escape = (str: string): string =>
  str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const WEEKDAY_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const heatmapLevel = (count: number): number => {
  if (count === 0) return 0;
  if (count <= 2) return 1;
  if (count <= 5) return 2;
  if (count <= 10) return 3;
  return 4;
};

export const renderHeader = (data: WeeklyReportData): string => `
  <header class="header">
    <img class="avatar" src="${escape(data.avatarUrl)}" alt="${escape(data.username)}" />
    <div class="header-text">
      <h1>${escape(data.username)}'s Weekly Report</h1>
      <p class="date-range">${escape(data.dateRange.from)} - ${escape(data.dateRange.to)}</p>
    </div>
  </header>
`;

export const renderStats = (data: WeeklyReportData): string => {
  const cards = [
    { value: data.stats.totalCommits, label: "Commits" },
    { value: data.stats.prsOpened, label: "PRs Opened" },
    { value: data.stats.prsMerged, label: "PRs Merged" },
    { value: data.stats.prsReviewed, label: "Reviews" },
    { value: data.stats.issuesOpened, label: "Issues Opened" },
    { value: data.stats.issuesClosed, label: "Issues Closed" },
  ];

  const cardHtml = cards
    .map(
      (c) => `
      <div class="stat-card">
        <div class="value">${c.value}</div>
        <div class="label">${c.label}</div>
      </div>`,
    )
    .join("");

  return `<div class="stats">${cardHtml}</div>`;
};

export const renderHeatmap = (dailyCommits: DailyCommitCount[]): string => {
  const days = dailyCommits
    .map((d) => {
      const date = new Date(d.date + "T00:00:00Z");
      const weekday = WEEKDAY_SHORT[date.getUTCDay()];
      const level = heatmapLevel(d.count);
      return `
        <div class="heatmap-day heatmap-level-${level}">
          <span class="count">${d.count}</span>
          <span>${weekday}</span>
        </div>`;
    })
    .join("");

  return `
    <div class="section">
      <h2>Contribution Graph</h2>
      <div class="heatmap">${days}</div>
    </div>
  `;
};

export const renderLanguages = (languages: LanguageBreakdown[]): string => {
  if (languages.length === 0) return "";

  const barSegments = languages
    .map(
      (l) =>
        `<div class="lang-bar-segment" style="width:${l.percentage}%;background:${l.color}"></div>`,
    )
    .join("");

  const list = languages
    .map(
      (l) => `
      <li>
        <span class="lang-dot" style="background:${l.color}"></span>
        <span>${escape(l.language)}</span>
        <span class="lang-pct">${l.percentage.toFixed(1)}%</span>
      </li>`,
    )
    .join("");

  return `
    <div class="section">
      <h2>Languages</h2>
      <div class="lang-bar">${barSegments}</div>
      <ul class="lang-list">${list}</ul>
    </div>
  `;
};

export const renderRepositories = (repos: RepositoryActivity[]): string => {
  if (repos.length === 0) return "";

  const rows = repos
    .map(
      (r) => `
      <tr>
        <td><a href="${escape(r.url)}">${escape(r.name)}</a></td>
        <td>${r.prsOpened}</td>
        <td>${r.prsMerged}</td>
        <td>${r.issuesOpened}</td>
      </tr>`,
    )
    .join("");

  return `
    <div class="section">
      <h2>Active Repositories</h2>
      <table class="repo-table">
        <thead><tr><th>Repository</th><th>PRs Opened</th><th>PRs Merged</th><th>Issues</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  `;
};

export const renderNarrative = (narrative: string | null): string => {
  if (!narrative) return "";

  const paragraphs = narrative
    .split("\n\n")
    .map((p) => `<p>${escape(p.trim())}</p>`)
    .join("");

  return `
    <div class="section">
      <h2>AI Summary</h2>
      <div class="narrative">${paragraphs}</div>
    </div>
  `;
};

export const renderFooter = (): string => `
  <footer class="footer">
    <p>Generated by <a href="https://deariary.com?utm_source=github-weekly-reporter&utm_medium=footer">deariary</a></p>
  </footer>
`;
